spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${USER_NAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    com.zaxxer.hikari: DEBUG

api:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}

